# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs: 
  elementor-plugin:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy app to server
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.KAS_HOST }}
          username: ${{ secrets.KAS_USERNAME }}
          password: ${{ secrets.KAS_PASSWORD }}
          script: 'cd /www/htdocs/w0138111/lkc.resize.rs/wp-content/themes/lkc-theme && ./deploy.sh'
